kind: wasmer.io/App.v0
name: wordpress # this can be overwritten in autobuild with the `--name` flag
package: .
capabilities:
  database:
    engine: mysql
volumes:
  - name: wp-content
    mount: /app/wp-content
